### ISSUE TITLE
when I use " export HAR",sometimes the  downloaded file is empty( 0kb )

### ISSUE THREAD

**Issue by fanxiaolong2000** [MicrosoftEdge/DevTools#287]
![image](https://github.com/user-attachments/assets/895c5c85-be1a-429a-8346-f3cea275e082)
the problem doesnt happend everytime but that also troubled me ,when i downloaded big data which i had waitted for several hours
please tell me how to handle it when i meet ,or tell me where the raw data saved ,then  i can save the net data in another ways  

AB#54855555

**Comment by leahmsft** [comment]
Thank you for reporting this issue. I will make sure it's on the engineering team's backlog.

**Comment by leahmsft** [comment]
Can you help provide details on what version of Edge you're using and OS?

**Comment by leahmsft** [comment]
Closing since this is resolved in Edge v131.

**Comment by wodeguaiguai** [comment]
This problem still exists in edge 134.0.3124.85. After I ran the data all night, I downloaded the data this morning.

![Image](https://github.com/user-attachments/assets/eb1f81a6-2dee-4e1b-8de8-82cc43f6acea)

![Image](https://github.com/user-attachments/assets/d3b4cc0e-e174-41eb-98f9-8694002a522d)

![Image](https://github.com/user-attachments/assets/d747f81b-f06d-49a3-9af0-3db01e2e03ab)
