### ISSUE TITLE
Known Issue: DevTools tools mostly appear blank

### ISSUE THREAD

**Issue by robpaveza** [MicrosoftEdge/DevTools#296]
Hello folks, my name is Rob; I'm an engineering manager on the DevTools team.

All versions of Edge DevTools are currently experiencing an issue in which tools appear blank. The Elements, Console, Sources, and Network tools all show no data, the "Close" button does not operate when docked, and undock buttons do not work. Your tools may look like this:

![image](https://github.com/user-attachments/assets/e7fd1002-9999-4ab8-a07b-acc1f720380d)

We are aware of this problem and are working on a fix. 

## Workaround

To successfully load DevTools, you must close the **Network Console** tool. This can be done by right-clicking on the tab and choosing "Close" (if you're in legacy-UI mode) or "Remove from Quick View" or "Remove from Activity Bar" (if you're in Focus Mode UI). Then, close DevTools by focusing on your inspected page and pressing F12 or Ctrl+Shift+I/Cmd+Shift+I. Re-launching DevTools should then work as expected.

## Expected fix timeline

This week is Thanksgiving in the United States, which means we are out of the office on November 28 and 29. However, we believe we will have at least a temporary fix checked in today, November 27, which should be able to go out in [Canary](https://www.microsoftedgeinsider.com/) early next week. We are also working on landing the fix in our next Stable update for Microsoft Edge 131.

AB#55263316

**Comment by robpaveza** [comment]
This issue has been resolved in the Canary channel as of 133.0.2995.0 and Stable as of 131.0.2903.86. A flight of Beta is expected some time next week which will also contain the fix.

**Comment by robpaveza** [comment]
This issue has now been resolved in the Beta channel as of 132.0.2957.41.

**Comment by moutartdc** [comment]
Hello,

I am still seeing this issue:

![Image](https://github.com/user-attachments/assets/32230e63-80e2-4357-9b92-1ad66128d728)

I am running Edge version: 132.0.2957.127

![Image](https://github.com/user-attachments/assets/3e8254c0-7672-426d-8706-64efb33bf0fb)

Any other fixes for this?

Thanks

**Comment by GoldenretriverYT** [comment]
Also happening to me on 132.0.2957.140

**Comment by gamliela** [comment]
Still happens at 142.0.3595.65

**Comment by thisVioletHydra** [comment]
144.0.3719.104
 
<img width="1069" height="886" alt="Image" src="https://github.com/user-attachments/assets/c4e4a41f-93b9-4fbb-812d-ebc97ed85197" />

**Comment by thisVioletHydra** [comment]
@robpaveza how to fix it?

**Comment by thejae** [comment]
Same issue is happening on Version 153.0.4234.32 (Official build) (64-bit)

**Comment by DeanLongmire** [comment]
Still happening nearly 2 years later in 153.0.4234.48 (Official build) (64-bit). Don't fix it idc I am never using edge again
