### ISSUE TITLE
Inspect Issue

### ISSUE THREAD

**Issue by Trevor-143** [MicrosoftEdge/DevTools#311]
Hey i have been having this problem when using edge. which is the only browser i like using on my pc. Am a developer and when am building and testing mobile apps and webapps in edge by right clicking and inspecting to get access to console, the windows disappears or pops out or just doesn't show up and when it down for the first few trials it goes to the bottom and when you set it to the right and you want to on the left, it could registered that its on the left and yet its on the right and you have to click both sides back and forth for it to agree with you... please look into it i use edge for everything especially for testing apps.

**Comment by leahmsft** [comment]
@Trevor-143 thank you for your feedback. Can you help me understand which version of Edge you're using? 
It sounds like you're experiencing 2 different problems:
1. DevTools sometimes does not open with right-clicking and clicking Inspect. Other times, the DevTools window opens as an undocked window and disappears.
2. The Dock location of the DevTools window isn't working as expecting. The dock location doesn't align with the option that is selected. In your case, when you select "Dock to left", the window is docked to the right.

Did I understand that correctly? Also, do the same issues happen if you open DevTools with F12 or Ctrl + Shift + I?

**Comment by usemain** [comment]
> [@Trevor-143](https://github.com/Trevor-143) thank you for your feedback. Can you help me understand which version of Edge you're using? It sounds like you're experiencing 2 different problems:
> 
> 1. DevTools sometimes does not open with right-clicking and clicking Inspect. Other times, the DevTools window opens as an undocked window and disappears.
> 2. The Dock location of the DevTools window isn't working as expecting. The dock location doesn't align with the option that is selected. In your case, when you select "Dock to left", the window is docked to the right.
> 
> Did I understand that correctly? Also, do the same issues happen if you open DevTools with F12 or Ctrl + Shift + I?

In version 132.0.2957.140, if I enable both mobile mode and PC mode developer tools on the same page, the following bug will appear.

![Image](https://github.com/user-attachments/assets/57b06e56-bb26-4375-b660-016cf1470c5b)
![Image](https://github.com/user-attachments/assets/b60f8012-4aeb-4c55-85d2-48fd40ff3834)

**Comment by leahmsft** [comment]
@usemain Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it?
Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?

I'm unable to reproduce this bug in v132, can you please list your repro steps?

**Comment by usemain** [comment]
> [@usemain](https://github.com/usemain) Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it? Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?
> 
> I'm unable to reproduce this bug in v132, can you please list your repro steps?
This is a video I just recorded after upgrading to version 133, and this issue still occurs, greatly affecting the development experience.
version:133.0.3065.59 (arm64)

**Comment by usemain** [comment]
> [@usemain](https://github.com/usemain) Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it? Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?
> 
> I'm unable to reproduce this bug in v132, can you please list your repro steps?

This is a video I just recorded after upgrading to version 133.0.3065.59, and this issue still occurs, greatly affecting the development experience.

https://github.com/user-attachments/assets/558484ce-2711-4a40-bda9-521798ec5124

**Comment by usemain** [comment]
> > [@usemain](https://github.com/usemain) Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it? Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?
> > I'm unable to reproduce this bug in v132, can you please list your repro steps?
> 
> This is a video I just recorded after upgrading to version 133.0.3065.59, and this issue still occurs, greatly affecting the development experience.

**Comment by Trevor-143** [comment]
> [@Trevor-143](https://github.com/Trevor-143) thank you for your feedback. Can you help me understand which version of Edge you're using? It sounds like you're experiencing 2 different problems:
> 
> 1. DevTools sometimes does not open with right-clicking and clicking Inspect. Other times, the DevTools window opens as an undocked window and disappears.
> 2. The Dock location of the DevTools window isn't working as expecting. The dock location doesn't align with the option that is selected. In your case, when you select "Dock to left", the window is docked to the right.
> 
> Did I understand that correctly? Also, do the same issues happen if you open DevTools with F12 or Ctrl + Shift + I?

Your right on the money

**Comment by Trevor-143** [comment]
> > [@Trevor-143](https://github.com/Trevor-143) thank you for your feedback. Can you help me understand which version of Edge you're using? It sounds like you're experiencing 2 different problems:
> > 
> > 1. DevTools sometimes does not open with right-clicking and clicking Inspect. Other times, the DevTools window opens as an undocked window and disappears.
> > 2. The Dock location of the DevTools window isn't working as expecting. The dock location doesn't align with the option that is selected. In your case, when you select "Dock to left", the window is docked to the right.
> > 
> > Did I understand that correctly? Also, do the same issues happen if you open DevTools with F12 or Ctrl + Shift + I?
> 
> In version 132.0.2957.140, if I enable both mobile mode and PC mode developer tools on the same page, the following bug will appear.
> 
> ![Image](https://github.com/user-attachments/assets/57b06e56-bb26-4375-b660-016cf1470c5b) ![Image](https://github.com/user-attachments/assets/b60f8012-4aeb-4c55-85d2-48fd40ff3834)

This is my experience too

**Comment by Trevor-143** [comment]
> > [@usemain](https://github.com/usemain) Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it? Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?
> > I'm unable to reproduce this bug in v132, can you please list your repro steps?
> 
> This is a video I just recorded after upgrading to version 133.0.3065.59, and this issue still occurs, greatly affecting the development experience.
> 
>  _Jietu20250212092025HD.mp4

This video is exactly what happens to me. I usually use dev tools on the right so getting to it I need to select other options and maybe move things around before settling on the right. Thanks again for the video

**Comment by Trevor-143** [comment]
Hey I didn't check what exactly my edge version was before now but at this point Am not getting this bug and am using v133 with a pending update. 

![Image](https://github.com/user-attachments/assets/1a0f0143-38e4-4978-a12e-c9ecc6205620)

**Comment by Trevor-143** [comment]
> Hey I didn't check what exactly my edge version was before now but at this point Am not getting this bug and am using v133 with a pending update.
> 
> ![Image](https://github.com/user-attachments/assets/1a0f0143-38e4-4978-a12e-c9ecc6205620)

I believe the issue was fixed

**Comment by leahmsft** [comment]
> > [@usemain](https://github.com/usemain) Thanks for the helpful screenshots! Are you seeing this bug when you open DevTools by right-clicking inspect? Or does it always appear regardless of the way it opens? Is DevTools docked to the bottom when you close it? Edge Stable 133 just released last week. Can you update to the latest version and let me know if you're still seeing the same thing?
> > I'm unable to reproduce this bug in v132, can you please list your repro steps?
> 
> This is a video I just recorded after upgrading to version 133.0.3065.59, and this issue still occurs, greatly affecting the development experience.
> 
>  _Jietu20250212092025HD.mp4

Thanks for your recording. I was able to reproduce this as well. I'll bring this to the engineering team for further investigation.

**Comment by leahmsft** [comment]
@usemain Can you try this workaround while the engineering team works on a fix?
1. Go to edge://flags
2. Search for the "Microsoft Edge rounded corners" experiment
3. Select "Disabled" in the dropdown and restart Edge

**Comment by Trevor-143** [comment]
Okay cool

**Comment by usemain** [comment]
> [@usemain](https://github.com/usemain) Can you try this workaround while the engineering team works on a fix?
> 
> 1. Go to edge://flags
> 2. Search for the "Microsoft Edge rounded corners" experiment
> 3. Select "Disabled" in the dropdown and restart Edge

Thank you. This issue has been resolved. Disabling this Microsoft Edge rounded corners will not cause any problems. This issue occurred in both versions, and previous versions had no problems.

**Comment by Looooooka** [comment]
OK. I found the issue.
I tried older versions of edge and visual studio code.
At one point I installed the user installer for vscode 1.96.4.exe ran it and it worked.
When I used my taskbar shortcut it wouldn't work. Not the user install or the system install.
So I checked that shortcut and of course it had the Run this program as administrator in the compatibility settings. Turning it off makes ALL my versions, the old user install, the current version system install and the current preview version install of Visual Studio Code debug with edge without issues.
So I'm guessing something with permissions changed in edge.
Hope this helps someone. Wasted half a day on this :)

**Comment by hCante** [comment]
> [@usemain](https://github.com/usemain) Can you try this workaround while the engineering team works on a fix?
> 
>     1. Go to edge://flags
> 
>     2. Search for the "Microsoft Edge rounded corners" experiment
> 
>     3. Select "Disabled" in the dropdown and restart Edge

Thanks for the solution, it works disabling MS Edge rouded corners. 
I can confirm it still happens as of today on macOS, Edge 133.0.3065.92.

**Comment by leahmsft** [comment]
The out of place content bug when multiple tabs are open has been fixed in Edge 135.0.3175.0. Our team is still working on fixing the incorrect dock location bug. Please continue to use the workaround in the meantime. Thanks for your patience.

**Comment by Trevor-143** [comment]
Thanks a lot cause that bug is kind of annoying.

**Comment by leahmsft** [comment]
The docking bug has been fixed in Edge 136.0.3194.0. 

Closing as completed.

**Comment by aryiu** [comment]
I had the same issue with the macOS version 134.0.3124.95 (arm64). Resolved disabling the "Microsoft Edge rounded corners" experiment in edge://flags.
