### ISSUE TITLE
"Edit and Resend" feature is not working in Version 139.0.3405.102  (Official build) (64-bit)

### ISSUE THREAD

**Issue by jmsfnch** [MicrosoftEdge/DevTools#359]
Similar to https://github.com/MicrosoftEdge/DevTools/issues/352 ,  the problem recurs on v 139.0.3405.102 

<img width="703" height="338" alt="Image" src="https://github.com/user-attachments/assets/b30fd6ee-7fb6-44fd-84e9-4802aa7f877e" />

**Comment by giorgiofellipe** [comment]
I can confirm it is not working for me either
`Version 139.0.3405.102 (Official build) (arm64)`

**Comment by erickdara** [comment]
Hi Guys the same error here with the Version 140.0.3485.66 (Official build) (64-bit)

<img width="3428" height="1250" alt="Image" src="https://github.com/user-attachments/assets/760dd73c-a008-409b-bd63-3002618d9188" />

Please check again. Thanks in advance.

**Comment by leahmsft** [comment]
Thanks for reporting. This has been fixed in 142.0.3558.0 (Official build).

**Comment by fuhao-w** [comment]
> Thanks for reporting. This has been fixed in 142.0.3558.0 (Official build).

Thanks for the fix! I can confirm it works in 142.0.3558.0. However, after updating to 142.0.3561.0 (Official Build) canary (64-bit), the 'Edit and Resend' feature seems to be broken again.

<img width="2544" height="1208" alt="Image" src="https://github.com/user-attachments/assets/7ff32267-fe08-474a-ab01-7dd529c82b0a" />

**Comment by leahmsft** [comment]
Thanks for letting us know. I'll share this with the team so we can re-investigate. Sorry about the inconvenience and thank you for your patience.

**Comment by leahmsft** [comment]
The fix is available in 142.0.3575.0. Please let us know if you run into any issues.

**Comment by edahlberg** [comment]
Seems still broken in version 142.0.3580.0 in a different way

Repro: 
1. Open F12
2. go to github.com
3. Take the first request and try to edit and resend it
4. **Status: 0 Compiler error.**

The UI is also very buggy - for instance, the "no collections" message persists after adding a collection...

**Comment by fuhao-w** [comment]
> Seems still broken in version 142.0.3580.0 in a different way
> 
> Repro:
> 
> 1. Open F12
> 2. go to github.com
> 3. Take the first request and try to edit and resend it
> 4. **Status: 0 Compiler error.**
> 
> The UI is also very buggy - for instance, the "no collections" message persists after adding a collection...

Version 142.0.3582.0 exhibits the same issue , I can provide a screenshot as additional evidence.

<img width="1211" height="749" alt="Image" src="https://github.com/user-attachments/assets/5c9e71f3-8811-4f12-a263-490c9b90629d" />

and I've also noticed that after clicking "Send," the current DevTools window can no longer be closed by clicking the "X" button in the top-right corner

<img width="1252" height="498" alt="Image" src="https://github.com/user-attachments/assets/47073ea2-2954-43a9-8d79-6b226cc9e34a" />
