### ISSUE TITLE
Edge 142 breaks React DevTools

### ISSUE THREAD

**Issue by AzureZeng** [MicrosoftEdge/DevTools#385]
After updating to v142.0.3595.53, React DevTools is broken, saying "Looks like this page doesn't have React, or it hasn't been loaded yet."

Tested on Chrome 142 and Edge 141, and there are no such bug.

<img width="1784" height="1023" alt="Image" src="https://github.com/user-attachments/assets/24bb9f93-ec5a-46a8-b24e-6fcd4ab47e59" />

**Comment by ganlvtech** [comment]
Same issue.

Test with React DevTools 7.0.1 and 6.1.5. Both can't run on Edge 142.

(React DevTools 7.0.1 + Chrome 142 is ok.)

```
Looks like this page doesn't have React, or it hasn't been loaded yet.
```

Use <kbd>Ctrl+Shift+I</kbd> open DevTools for DevTools.

console log

```
Extension server error: Operation failed: Permission denied
e @ extensions.js:5
onmessage @ extensions.js:5
```

exception

```
Session is unregistering, can't dispatch pending call to Runtime.evaluate"
```

**Comment by wxupjack** [comment]
Same issue on macOS arm64 Edge 142.0.3595.53. Also, once you activate `React DevTools Components` or `Profiler` tabs, the DevTools panel cannot be closed.

- switch to old DevTools not work
- enable allow access to file urls not work
- reinstall React DevTools/Edge not work

**Comment by saschadiercks** [comment]
This seems to be a general issue with the DevTools, since ArcToolkit is also not working anymore.

<img width="729" height="157" alt="ARC Toolkit Extension in DevTools" src="https://github.com/user-attachments/assets/2d9dc547-5b91-498e-b0cd-c21eec995997" />

Also when switching the position of the DevTools, while being on a "broken" extension (eg.: from bottom to right or vice versa) the layout gets messed up. In that case, the close-icon of the DevTools is no longer working. They can only be closed through a key-combo in that case (CMD + ALT + I).

<img width="1709" height="1127" alt="Broken DevTools Layout after switching position" src="https://github.com/user-attachments/assets/c2711d30-ed0c-4d9b-9df9-e0f0d3fa57a2" />

**Comment by SunsetTechuila** [comment]
Opening React DevTools tab breaks all the built-in tools: Elements, Console, Sources - nothing works until you reopen the DevTools window. Edge QA is a joke (not a funny one)

**Comment by leahmsft** [comment]
Thank you all for sharing details on this issue. The engineering team is currently looking into this.

**Comment by dews** [comment]
Also, the Vue.js devtools https://chromewebstore.google.com/detail/vuejs-devtools/iaajmlceplecbljialhhkmedjlpdblhp?pli=1

**Comment by jonathan-x01** [comment]
> Same issue on macOS arm64 Edge 142.0.3595.53. Also, once you activate `React DevTools Components` or `Profiler` tabs, the DevTools panel cannot be closed.
> 
> * switch to old DevTools not work
> * enable allow access to file urls not work
> * reinstall React DevTools/Edge not work

Not just that, you also cannot refresh the page at all either, you have to close the tab and open a new tab. So, it pretty much breaks the entire tab.

**Comment by omarqra** [comment]
This is very annoying, it is not working for my next.js projects too
I had to move to `npx react-devtools` for now

**Comment by seanputera** [comment]
Same goes for GraphQL Network Inspector https://chromewebstore.google.com/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln

**Comment by tsulli** [comment]
I updated to Version 142.0.3595.65 (Official build) (64-bit) this morning and it has not fixed the issue. Vue.js dev tools extension will still cause Edge dev tools to lock up the whole tab until it is closed and reopened - making Vue development in Edge extremely difficult. 

Vue.js dev tools extension continues to work as expected in Chrome Version 142.0.7444.135 (Official Build) (64-bit)

**Comment by HadarZ** [comment]
I upgraded to version 142.0.3595.69 and the issue is resolved.

**Comment by AzureZeng** [comment]
<img width="1512" height="982" alt="Image" src="https://github.com/user-attachments/assets/01cbb0ef-34c4-417c-a4d3-58f5a772df50" />

Confirmed that this issue is solved by updating Microsoft Edge.

**Comment by wxupjack** [comment]
> Confirmed that this issue is solved by updating Microsoft Edge.

What your current Edge version?  Mine is 142.0.3595.**65**.  It works at the first time, but still crashes after several attempts.

**Comment by AzureZeng** [comment]
> > Confirmed that this issue is solved by updating Microsoft Edge.
> 
> What your current Edge version? Mine is 142.0.3595.**65**. It works at the first time, but still crashes after several attempts.

I found this, so I reopend this issue.

**Comment by AzureZeng** [comment]
> > Confirmed that this issue is solved by updating Microsoft Edge.
> 
> What your current Edge version? Mine is 142.0.3595.**65**. It works at the first time, but still crashes after several attempts.

Seems 142.0.3595.69 is ONLY available in Windows platform so Mac/Linux user still need to wait for the 142.0.3595.69 patch.

**Comment by bobvandevijver** [comment]
Can confirm that 142.0.3595.69 fixes the issue.

**Comment by leahmsft** [comment]
Thank you all for your patience. The fix is in v142.0.3595.69 which was only released to Windows, and it will be available for Mac/Linux in the release this Thursday (11/13). 

Thank you again for reporting these issues and helping us improve the product. The engineering team is committed to enhancing testing to prevent this issue in the future.

**Comment by SunsetTechuila** [comment]
> Thank you again for reporting these issues and helping us improve the product.

It's a disgrace that your team didn't catch such an obvious and serious issue. You should be sorry, not thankful
